import { readFile, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createRequire } from "node:module";
const root = JSON.parse(
  await readFile(new URL("../package.json", import.meta.url), "utf8"),
);
const visited = new Set();
const notices = new Map();
async function visit(
  name,
  parent = new URL("../package.json", import.meta.url),
) {
  const require = createRequire(parent);
  // Read the package manifest without relying on public package exports.
  const search = require.resolve.paths(name);
  let folder, manifest;
  for (const path of search) {
    try {
      folder = resolve(path, name);
      manifest = JSON.parse(
        await readFile(resolve(folder, "package.json"), "utf8"),
      );
      break;
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }
  if (!manifest) throw new Error(`Missing package ${name}`);
  const key = `${manifest.name}@${manifest.version}`;
  if (visited.has(key)) return;
  visited.add(key);
  const files = (await readdir(folder))
    .filter((file) => /^(license|copying|notice)([.-]|$)/i.test(file))
    .sort();
  if (!files.length) throw new Error(`Missing license for ${key}`);
  const text = (
    await Promise.all(
      files.map((file) => readFile(resolve(folder, file), "utf8")),
    )
  ).join("\n\n");
  notices.set(key, `## ${key}\n\n${text.trim()}\n`);
  for (const dependency of Object.keys(manifest.dependencies || {}))
    await visit(dependency, resolve(folder, "package.json"));
}
for (const name of [
  ...Object.keys(root.dependencies),
  "workbox-precaching",
  "workbox-routing",
])
  await visit(name);
await writeFile(
  new URL("../THIRD_PARTY_NOTICES.md", import.meta.url),
  "# Frontend third-party notices\n\nGenerated by `npm run notices`; includes bundled runtime dependencies.\n\n" +
    [...notices]
      .sort(([a], [b]) => a.localeCompare(b, "en"))
      .map(([, text]) => text)
      .join("\n"),
);
