// Copyright 2026 Timon Gentzsch

#include "include/app/reference.h"

#include <algorithm>
#include <string>
#include <vector>

#include "include/app/self_description.h"
#include "include/core/fs.h"
#include "include/core/json.h"
#include "include/core/limits.h"
#include "include/core/strings.h"

namespace uagent {
namespace {

const char kGenerated[] =
    "<!-- Generated by `uagent --emit-reference`. Edit the registries in\n"
    "     src/, not this file; CI fails when the two disagree. -->\n\n";

// A table cell is one line. A tool description may not be — the skill
// catalogue is a list — so a newline becomes a break rather than splitting the
// row and silently corrupting the table.
std::string Escape(const std::string& text) {
  std::string out;
  out.reserve(text.size());
  for (char character : text) {
    if (character == '|') {
      out += '\\';
    } else if (character == '\n') {
      out += "<br>";
      continue;
    }
    out += character;
  }
  return out;
}

std::string DefaultCell(const json& setting) {
  const json& value = setting["default"];
  if (value.is_null()) return "derived";
  if (value.is_string()) {
    std::string text = value.get<std::string>();
    return text.empty() ? "empty" : "`" + Escape(text) + "`";
  }
  if (value.is_boolean()) return value.get<bool>() ? "`1`" : "`0`";
  return "`" + JsonDump(value) + "`";
}

std::string CliMarkdown() {
  std::string out = "# Command-line flags\n\n";
  out += kGenerated;
  out += "| Flag | Value | Description |\n| --- | --- | --- |\n";
  for (const json& flag : CliSchemaJson()) {
    out += "| `" + JsonValue(flag, "flag", std::string()) + "` | " +
           (flag.contains("value")
                ? "`" + JsonValue(flag, "value", std::string()) + "`"
                : "—") +
           " | " + Escape(JsonValue(flag, "description", std::string())) +
           " |\n";
  }
  out +=
      "\nPrecedence: these flags override process `UAGENT_*` variables, which "
      "override a trusted `./.uagent/.config`, which overrides "
      "`~/.uagent/.config`.\n";
  return out;
}

std::string CommandsMarkdown() {
  std::string out = "# Slash commands\n\n";
  out += kGenerated;
  out += "| Command | Description |\n| --- | --- |\n";
  for (const json& command : CommandSchemaJson()) {
    out += "| `" + JsonValue(command, "usage", std::string()) + "` | " +
           Escape(JsonValue(command, "description", std::string())) + " |\n";
  }
  return out;
}

std::string ConfigMarkdown() {
  json settings = ConfigSchemaJson();
  std::vector<std::string> categories;
  for (const json& setting : settings) {
    std::string category = JsonValue(setting, "category", std::string());
    if (std::find(categories.begin(), categories.end(), category) ==
        categories.end()) {
      categories.push_back(category);
    }
  }
  std::string out = "# Configuration\n\n";
  out += kGenerated;
  out +=
      "Every setting below is read from the running binary's registry. "
      "`takes effect` is `next-user-turn` when a change to a config file "
      "applies at the next prompt, and `restart-required` when it does not. "
      "Secret values are never displayed; diagnostics report only whether they "
      "are set.\n";
  // A contents list, because this is the one reference long enough that a
  // reader previewing the head of it would otherwise see only the first few
  // categories and conclude the rest are missing.
  out += "\n## Contents\n\n";
  for (const std::string& category : categories) {
    out += "- " + category + "\n";
  }
  for (const std::string& category : categories) {
    out += "\n## " + category + "\n\n";
    out +=
        "| Setting | Type | Default | Takes effect | Description |\n"
        "| --- | --- | --- | --- | --- |\n";
    for (const json& setting : settings) {
      if (JsonValue(setting, "category", std::string()) != category) continue;
      std::string name = JsonValue(setting, "name", std::string());
      if (JsonValue(setting, "sensitivity", std::string()) != "public") {
        name += " 🔒";
      }
      out += "| `" + name + "` | " + JsonValue(setting, "type", std::string()) +
             " | " + DefaultCell(setting) + " | " +
             JsonValue(setting, "takes_effect", std::string()) + " | " +
             Escape(JsonValue(setting, "description", std::string())) + " |\n";
    }
  }
  return out;
}

// The prompt is the one input to model behavior that no test can fully assert,
// so it is emitted verbatim: a wording change becomes a reviewable diff here
// exactly like a changed configuration default.
std::string PromptMarkdown() {
  json surface = PromptSurfaceJson();
  std::string out = "# System prompt\n\n";
  out += kGenerated;
  out +=
      "This is the immutable base every session starts from. Host "
      "capabilities, runtime context, project instructions, the memory index "
      "and any mutable self-directive are assembled per session and recorded "
      "by `--debug`. `UAGENT_PROMPT_OVERLAY` may replace the sections listed "
      "below for an experiment; it changes prompt text only.\n\n";
  out += "## Base (" +
         std::to_string(JsonValue(surface, "base_chars", int64_t{0})) +
         " chars)\n\n```text\n" + JsonValue(surface, "base", std::string()) +
         "\n```\n\n## Capability fragments\n\nEach fragment is appended only "
         "when its trigger tool is registered.\n";
  for (const json& fragment : surface["capability_fragments"]) {
    out += "\n### " + JsonValue(fragment, "trigger", std::string()) +
           "\n\n```text\n" + Trim(JsonValue(fragment, "text", std::string())) +
           "\n```\n";
  }
  return out;
}

std::string ToolsMarkdown() {
  std::string out = "# Built-in tool surface\n\n";
  out += kGenerated;
  out +=
      "Descriptions are what the model reads, including the batching and "
      "budget suffixes the registry appends. `bytes` is what one schema costs "
      "in every request that advertises it, and `when` says which sessions "
      "pay it. `schema` digests the complete JSON parameters, so an argument "
      "or its description cannot change without changing this table. "
      "Conditionally registered tools are rendered from empty dependencies: "
      "the route- and skill-catalogue text a live session splices in, and MCP "
      "tools, appear in `/context` instead.\n\n";
  json surface = ToolSurfaceJson();
  size_t total = 0;
  size_t always = 0;
  for (const json& tool : surface) {
    size_t bytes = JsonDump(tool["parameters"]).size() +
                   JsonValue(tool, "description", std::string()).size();
    total += bytes;
    if (JsonValue(tool, "when", std::string()) == "always") always += bytes;
  }
  out += "Advertised schema text totals " + std::to_string(total) +
         " bytes, of which " + std::to_string(always) +
         " bytes are sent by every session.\n\n";
  out +=
      "| Tool | Bytes | Arguments | Lean | Batchable | When | Schema | "
      "Description |\n| --- | --- | --- | --- | --- | --- | --- | --- |\n";
  for (const json& tool : surface) {
    const json& parameters = tool["parameters"];
    std::vector<std::string> required;
    if (parameters.contains("required")) {
      for (const json& name : parameters["required"]) {
        required.push_back(name.get<std::string>());
      }
    }
    std::string arguments;
    for (const auto& [name, unused] : parameters["properties"].items()) {
      if (!arguments.empty()) arguments += ", ";
      arguments += name;
      if (std::find(required.begin(), required.end(), name) == required.end()) {
        arguments += "?";
      }
    }
    const std::string description =
        JsonValue(tool, "description", std::string());
    out += "| `" + JsonValue(tool, "name", std::string()) + "` | " +
           std::to_string(JsonDump(parameters).size() + description.size()) +
           " | " +
           (arguments.empty() ? "\u2014" : "`" + Escape(arguments) + "`") +
           " | " + (JsonValue(tool, "lean", false) ? "yes" : "no") + " | " +
           (JsonValue(tool, "parallel_safe", false) ? "yes" : "no") + " | " +
           JsonValue(tool, "when", std::string()) + " | `" +
           HashHex(JsonDump(parameters)).substr(0, 12) + "` | " +
           Escape(description) + " |\n";
  }
  return out;
}

}  // namespace

json ReferenceManifestJson() {
  json settings = ConfigSchemaJson();
  return {{"version", kVersion},
          {"settings", settings.size()},
          {"flags", CliSchemaJson().size()},
          {"commands", CommandSchemaJson().size()},
          {"schema_digest",
           HashHex(JsonDump(json{{"config", settings},
                                 {"cli", CliSchemaJson()},
                                 {"commands", CommandSchemaJson()}}))},
          // The bytes that steer the model get the same drift gate as the
          // bytes that configure it.
          {"prompt_digest", HashHex(JsonDump(PromptSurfaceJson()))},
          {"tools_digest", HashHex(JsonDump(ToolSurfaceJson()))}};
}

json BuildProvenanceJson() {
  const json manifest = ReferenceManifestJson();
  json surface = {{"schema", manifest["schema_digest"]},
                  {"tools", manifest["tools_digest"]}};
  json provenance = {
      {"format", 1},
      {"binary_version", manifest["version"]},
      {"prompt_digest", manifest["prompt_digest"]},
      {"surface_digest", HashHex(JsonDump(surface))},
  };
  // A deterministic release identity, not a host, path, timestamp or other
  // value that can split equivalent cohorts or disclose local state.
  provenance["build_id"] = HashHex(JsonDump(provenance));
  return provenance;
}

std::string ReferenceManifest() {
  return JsonDump(ReferenceManifestJson(), 2) + "\n";
}

std::vector<ReferenceFile> ReferenceFiles() {
  return {{"cli.md", CliMarkdown()},
          {"slash-commands.md", CommandsMarkdown()},
          {"configuration.md", ConfigMarkdown()},
          {"system-prompt.md", PromptMarkdown()},
          {"tools.md", ToolsMarkdown()},
          {"manifest.json", ReferenceManifest()}};
}

bool WriteReferenceFiles(const std::string& directory, std::string& error) {
  for (const ReferenceFile& file : ReferenceFiles()) {
    if (!AtomicWriteFile(directory + "/" + file.name, file.contents,
                         kSharedFileMode, /*preserve_mode=*/false, error)) {
      return false;
    }
  }
  return true;
}

}  // namespace uagent
