# Embed the checked-in public bundle. No frontend tooling in native builds.
file(GLOB_RECURSE _web_assets CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/web/dist/*")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_web_assets})
set(_web_generated "${CMAKE_CURRENT_BINARY_DIR}/web_assets.cc")
file(WRITE "${_web_generated}" "#include \"include/web/assets.h\"\nnamespace uagent::web {\n")
set(_web_rows "")
set(_web_index 0)
foreach(_web_file IN LISTS _web_assets)
  file(RELATIVE_PATH _web_path "${CMAKE_CURRENT_SOURCE_DIR}/web/dist" "${_web_file}")
  get_filename_component(_web_ext "${_web_file}" LAST_EXT)
  set(_web_mime "application/octet-stream")
  if(_web_ext STREQUAL ".html")
    set(_web_mime "text/html; charset=utf-8")
  elseif(_web_ext STREQUAL ".js")
    set(_web_mime "text/javascript; charset=utf-8")
  elseif(_web_ext STREQUAL ".css")
    set(_web_mime "text/css; charset=utf-8")
  elseif(_web_ext STREQUAL ".webmanifest")
    set(_web_mime "application/manifest+json")
  elseif(_web_ext STREQUAL ".png")
    set(_web_mime "image/png")
  elseif(_web_ext STREQUAL ".woff2")
    set(_web_mime "font/woff2")
  elseif(_web_ext STREQUAL ".woff")
    set(_web_mime "font/woff")
  elseif(_web_ext STREQUAL ".ttf")
    set(_web_mime "font/ttf")
  endif()
  file(READ "${_web_file}" _web_hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," _web_hex "${_web_hex}")
  file(APPEND "${_web_generated}" "static const unsigned char kAsset${_web_index}[] = {${_web_hex}0};\n")
  string(APPEND _web_rows "{\"/${_web_path}\",\"${_web_mime}\",kAsset${_web_index},sizeof(kAsset${_web_index})-1},\n")
  math(EXPR _web_index "${_web_index}+1")
endforeach()
file(APPEND "${_web_generated}" "static const Asset kAssets[] = {${_web_rows}};\nstd::span<const Asset> Assets() { return kAssets; }\n}  // namespace uagent::web\n")
