# Embed the checked-in public bundle. The frontend promotes a complete bundle
# atomically and writes its file list last, so CMake never glob-reads a Vite
# directory while it is being emptied and rebuilt.
set(_web_root "${CMAKE_CURRENT_SOURCE_DIR}/web/dist")
set(_web_manifest "${_web_root}/.assets")
if(NOT EXISTS "${_web_manifest}")
  message(FATAL_ERROR "web/dist is empty or missing: run `npm run build` in web/ to generate the PWA bundle, or configure with -DUAGENT_WEB=OFF for a headless-only binary")
endif()
file(STRINGS "${_web_manifest}" _web_paths)
set(_web_assets "")
foreach(_web_path IN LISTS _web_paths)
  if(_web_path STREQUAL "" OR _web_path MATCHES "(^/|(^|/)\\.\\.(/|$))")
    message(FATAL_ERROR "invalid web asset path in ${_web_manifest}: ${_web_path}")
  endif()
  set(_web_file "${_web_root}/${_web_path}")
  if(NOT EXISTS "${_web_file}")
    message(FATAL_ERROR "web asset listed but missing: ${_web_path}; rerun `npm run build` in web/")
  endif()
  list(APPEND _web_assets "${_web_file}")
endforeach()
if(NOT _web_assets)
  message(FATAL_ERROR "web asset manifest is empty: rerun `npm run build` in web/")
endif()
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_web_manifest}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${_web_assets})
set(_web_generated "${CMAKE_CURRENT_BINARY_DIR}/web_assets.cc")
file(WRITE "${_web_generated}" "#include \"include/web/assets.h\"\nnamespace uagent::web {\n")
set(_web_rows "")
set(_web_index 0)
foreach(_web_file IN LISTS _web_assets)
  file(RELATIVE_PATH _web_path "${_web_root}" "${_web_file}")
  get_filename_component(_web_ext "${_web_file}" LAST_EXT)
  set(_web_mime "application/octet-stream")
  if(_web_ext STREQUAL ".html")
    set(_web_mime "text/html; charset=utf-8")
  elseif(_web_ext STREQUAL ".js")
    set(_web_mime "text/javascript; charset=utf-8")
  elseif(_web_ext STREQUAL ".css")
    set(_web_mime "text/css; charset=utf-8")
  elseif(_web_ext STREQUAL ".webmanifest")
    set(_web_mime "application/manifest+json")
  elseif(_web_ext STREQUAL ".png")
    set(_web_mime "image/png")
  elseif(_web_ext STREQUAL ".woff2")
    set(_web_mime "font/woff2")
  elseif(_web_ext STREQUAL ".woff")
    set(_web_mime "font/woff")
  elseif(_web_ext STREQUAL ".ttf")
    set(_web_mime "font/ttf")
  endif()
  file(READ "${_web_file}" _web_hex HEX)
  string(REGEX REPLACE "(..)" "0x\\1," _web_hex "${_web_hex}")
  file(APPEND "${_web_generated}" "static const unsigned char kAsset${_web_index}[] = {${_web_hex}0};\n")
  string(APPEND _web_rows "{\"/${_web_path}\",\"${_web_mime}\",kAsset${_web_index},sizeof(kAsset${_web_index})-1},\n")
  math(EXPR _web_index "${_web_index}+1")
endforeach()
file(APPEND "${_web_generated}" "static const Asset kAssets[] = {${_web_rows}};\nstd::span<const Asset> Assets() { return kAssets; }\n}  // namespace uagent::web\n")
